# Generated by Django 4.0.3 on 2023-02-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(max_length=10000000)),
                ('yourName', models.CharField(max_length=10000000)),
            ],
        ),
    ]
