# Generated by Django 4.0.3 on 2023-02-12 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomName',
            new_name='chatRoom',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='yourName',
            new_name='usersName',
        ),
        migrations.AddField(
            model_name='room',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
