# Generated by Django 4.0.3 on 2023-02-12 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_roomname_room_chatroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10000000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.CharField(max_length=10000000)),
                ('room', models.CharField(max_length=10000000)),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='chatRoom',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='usersName',
        ),
    ]
