# Generated by Django 4.1.6 on 2023-02-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_room_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room',
        ),
    ]
