# Generated by Django 4.1.6 on 2023-02-17 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_room_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.room'),
            preserve_default=False,
        ),
    ]
