# Generated by Django 4.1.6 on 2023-02-18 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sec',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='account.room'),
            preserve_default=False,
        ),
    ]
