# Generated by Django 4.1.6 on 2023-02-18 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_message_sec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sec',
        ),
    ]
